<h1>You are now logged in!</h1>

<div class="content-tile">
    <p><b>Enjoy the hidden content!</b></p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam repellendus, atque nesciunt commodi ut laboriosam tempore accusantium magnam totam libero ex necessitatibus. Eos ullam aliquid eveniet voluptates repudiandae unde temporibus, doloribus illum ipsum perspiciatis placeat quidem excepturi necessitatibus maiores ut eaque modi eius! Error praesentium assumenda maiores corporis? Sequi non ullam cumque, assumenda ratione voluptatibus ipsum corporis, quaerat magnam architecto, harum molestias alias!</p>
    <p>Nisi iste voluptatibus eius minus? Modi, veritatis quas voluptate, porro perferendis veniam rerum voluptas deserunt minima consectetur suscipit neque quos? Dolore sed magnam quis quo in esse modi iure! Rerum aspernatur eos voluptatibus, dignissimos tempore sit suscipit, dolore soluta, quis libero minima. Voluptatem consequuntur non laborum, corporis cupiditate numquam ut iste pariatur quaerat molestias blanditiis modi debitis doloribus optio amet suscipit officia. Omnis dolorum blanditiis beatae accusamus iure. Ratione nostrum, consectetur temporibus enim ut mollitia explicabo similique quo? Praesentium officia debitis omnis rerum iste nemo. Quos tempore ab illum impedit iusto dolore eaque molestias optio deserunt. Sapiente aspernatur sequi iusto, eos nesciunt sint accusantium voluptate rem eius laborum possimus natus et harum voluptatum alias. Quia ratione laboriosam et, accusantium numquam illum autem eveniet labore vel commodi impedit, sequi possimus, natus nulla adipisci inventore veritatis molestias.</p>
    <p>Cumque excepturi maiores aliquid quisquam hic libero iste veniam repellat, delectus adipisci enim doloribus, dolores suscipit, expedita reiciendis necessitatibus? Enim quidem qui quasi earum, cupiditate eveniet consequatur obcaecati quae, maiores consectetur sint esse id dicta nobis eius iure culpa voluptate similique tenetur velit quod!</p>
</div>

<canvas id="canvas" style="position: absolute; top: 0; left: 0; width: 100vw; height: 100vh; z-index: -50;">Sorry. Something went wrong with your canvas ... :/</canvas>
<script type="module" src="/js/bubble.js"></script>
